services:
  db:
    image: postgres:17
    container_name: josue-postgres

    environment:
      POSTGRES_DB: bd_josue_blanco
      POSTGRES_USER: josue
      POSTGRES_PASSWORD: 123456

    ports:
      - "5433:5432"

    volumes:
      - josue-db-data:/var/lib/postgresql/data

volumes:
  josue-db-data:
